### ISSUE TITLE
kicad-dev-snap

### ISSUE THREAD

**Issue by Scottapotamas** [eldarkg/kicad-snap#11]
I've seen there was an effort towards providing snaps for the dev branch to provide like 'nightly' support.

What is the status/support of this? 

I've been trying to improve the accessibility of 'nightly' builds, mostly so I can keep my Solus install inline with my work Win10 machine. I don't really know much about snaps, but happy to help maintain things.

**Comment by eldarkg** [comment]
@Scottapotamas now I temporarily stopped because I have little time.
I will be glad to your help.

**Comment by eldarkg** [comment]
@Scottapotamas The first try to resolve build error.
[See the build log](https://build.snapcraft.io/user/eldarkg/kicad-snap/41590)
